name: Test Docker Container
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run poDTest
        uses: h4nz0x/poDTest@v1
        with:
          dockerfile-path: ./deployments
          port: 9000
          health-check-path: /health
          health-check-timeout: 10
          health-check-interval: 5
          build-timeout: 300
          hot-fix: false
